name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - networkx
  - pandas
  - ipykernel
  - matplotlib
  - seaborn
  - pyvis
  # GNN off-target link prediction
  - pytorch
  - pip
  - pip:
    - torch-geometric>=2.4
